### ISSUE TITLE
The game crashes with kernel 3.17.7 and later

### ISSUE THREAD

**Issue by eydee** [KillaW0lf04/The-Witcher-2-Issues#89]
Steam community thread:
http://steamcommunity.com/app/20920/discussions/0/620700960252675402/

My log:
http://pastebin.com/EDTBiuXC

Others have similar symptoms.

**Comment by FrostbittenKing** [comment]
Found the offending commit in the linux kernel. Details here: http://steamcommunity.com/app/20920/discussions/0/620700960252675402/#c616199736993636877

**Comment by FrostbittenKing** [comment]
http://www.spinics.net/lists/stable/msg73672.html. According to this mailing list, it sounds to me like it is a bug in witcher2, although I would guess it has something to do with eon!.
Whatever they do with tls, it seems like they installed custom code segments into the GDT or set the so-called L-Bit (whatever that is, in a region they should not fiddle with). 
Prior to this patch they let that slide if it is the custom code segments, or if it is the L-Bit, then this wouldn't have changed anything. According to the mailing list, prior they silently dropped this setting of the L-Bit, but now they throw an error back.
What ever it is of the 2 cases, there is something going on, that the kernel devs deem to be suspicious.

**Comment by vpltd-peterm** [comment]
Thanks for tracking this down for us :)

Seems a bit suspicious that glibc and wine are not affected but we are.. when i read the source code to both to find out how to set up an LDT segment for FS from both of those!! Someone on the linux kernel dev team with an agenda, me thinks...

We will look into patching it

**Comment by vpltd-peterm** [comment]
The problem is caused by the definition of /usr/include/asm/ldt.h. Basically, if you dont bzero() any use of struct user_desc, even if you correctly fill all available fields, you get caught by this problem.

Thing is, for a 32 bit process, the "lm" field they are checking does not exist. The kernel should be ignoring this for a 32 bit process, or should be defaulting it to a sane value. 

Anyway, we can fix this and we'll try to do a patch shortly

**Comment by FrostbittenKing** [comment]
Nice. Well regarding the 32 bit processes, I don't understand the details but according to the commit message and the mailing list, allowing this opens an "interesting" attack vectors. Whatever the reason but this espfix thingy can be circumvented to do kinky shenanigans. 
If I understand you correctly, you are working outside the specification. You are using/creating/injecting (don't know) the lm field, although it doesn't exist for 32 bit processes, which obviously can be seen as abuse. Correct me if I'm wrong.
And if I think about it again, as I already mentioned setting the l(m) bit doesn't do anything anyway, since they dropped this command silently in this context, prior to the patch.

**Comment by vpltd-peterm** [comment]
No, we are not doing anything undocumented. I did check against WINE though, and they define their own version of the user_desc structure. In it they have a "garbage" field which covers lm, and any empty space. They set this field to zero. That is why they are unaffected. A bzero() on the user_desc structure before filling it in will have the same effect

**Comment by FrostbittenKing** [comment]
Oh, ok. Thanks for clearing that up. Thanks for fixing this. Learned something new.
Bisecting is awesome :).

**Comment by vpltd-peterm** [comment]
Tracked this down to something else actually.. we were requesting an LDT slot in a seperate call with an otherwise-zeroed user_desc. This is apparently now illegal. I simplified the code greatly, and while I havent tested it yet, it should fix the problem for sure.

Regards comments about the "Someone on the linux kernel dev team with an agenda, me thinks" comment, sure I was having a bad day - but it would not be the first time the Linux kernel team have sabotaged a closed source product. After all, they love moving goalposts for nVidia's binary driver...

**Comment by hvr** [comment]
> but it would not be the first time the Linux kernel team have sabotaged a closed source product. After all, they love moving goalposts for nVidia's binary driver...

Fwiw, there's an important difference here: The nVidia driver uses kernel-spaces APIs which are subject to change. Otoh, @torvalds recently stated to have [one major rule: don't break user-space](http://youtu.be/1Mg5_gxNXTo?t=8m35s). So if you you detected such a breakage, you should definitely report it to the Linux kernel developers.

**Comment by licaon-kter** [comment]
@hvr: He said it first a while back: https://lkml.org/lkml/2012/12/23/75 :P

**Comment by FrostbittenKing** [comment]
[quote]Tracked this down to something else actually.. we were requesting an LDT slot in a seperate call with an otherwise-zeroed user_desc. This is apparently now illegal. 
[/quote]

I think I understand what you mean:
[code]
+static bool tls_desc_okay(const struct user_desc *info)
+{
+	if (LDT_empty(info))
+		return true;
+
+	/*
+	 * espfix is required for 16-bit data segments, but espfix
+	 * only works for LDT segments.
+	 */
+	if (!info->seg_32bit)
+		return false;
+
+	return true;
+}
[/code]
It checks if the user_desc is zeroed, and if not it returns an error if seg_32bit is not set. Right?

**Comment by vpltd-peterm** [comment]
Yep, now we're doing this:
```
static bool setup_teb_register( const TEB* teb )
{
	// The first time we run, request that the kernel allocate us an LDT slot to use for our selector
	static int ldt_slot = -1;

	struct user_desc u_info;
	bzero(&u_info, sizeof(struct user_desc));

	u_info.entry_number = ldt_slot;
	u_info.base_addr = (uint32_t)teb;
	u_info.limit = sizeof(TEB) - 1;
	u_info.seg_32bit = 1;   // 32-bit data
	u_info.contents = MODIFY_LDT_CONTENTS_DATA;
	u_info.read_exec_only = 0;
	u_info.limit_in_pages = 1;
	u_info.seg_not_present = 0;
	u_info.useable = 1;

	if( syscall( SYS_set_thread_area, &u_info ) == -1 )
	{
		EON_LOG_ERROR( "setup_teb_register() - SYS_set_thread_area failed, errno %d", errno );
		return false;
	}

	// Now that we have an LDT entry to use, remember it for future use
	if (ldt_slot == -1)
	{
		ldt_slot = u_info.entry_number;
		EON_LOG_INFO("setup_teb_register() - using LDT entry %u", u_info.entry_number);
	}

	uint16_t sel = (uint16_t) ( ( ( u_info.entry_number & 0x1FFF ) << 3 ) | 3 );	// SEL_GDT | USER_PRIV
	asm volatile ( "mov %0, %%fs" : : "r" ( sel ) );
	return true;
}
```

In this instance, they broke userspace :)

**Comment by torvalds** [comment]
Andy,

 Looks like the LDT tightening actually broke a user app:

On Thu, Jan 22, 2015 at 1:19 AM, FrostbittenKing
<notifications@github.com> wrote:
> [quote]Tracked this down to something else actually.. we were requesting an
> LDT slot in a seperate call with an otherwise-zeroed user_desc. This is
> apparently now illegal.
> [/quote]

Also see

  http://steamcommunity.com/app/20920/discussions/0/620700960252675402/#c616199736993636877
  https://github.com/KillaW0lf04/The-Witcher-2-Issues/issues/89#issuecomment-70829298

so we'll need to revert or relax it. Possibly some of the checks could
be optional, so that they could just be disabled on servers etc who
worry more about attack surfaces than about games.

Can somebody specify exactly what the LDT entry was? The github email
address hopefully reaches a game developer too (Peter Mulholland). It
would be nice to keep the checks tight - just not *too* tight. And no,
you guys should *not* need to change user space app details, because
the kernel "don't break apps" rule really takes precedence.

And maybe this is an excuse for somebody in the x86 maintainer team to
try a few games on steam. They *are* likely good tests of odd
behavior..

              Linus

**Comment by torvalds** [comment]
On Jan 21, 2015 7:31 AM, "Linus Torvalds" <torvalds@linux-foundation.org>
wrote:
>
> Andy,
>
>  Looks like the LDT tightening actually broke a user app:
>
> On Thu, Jan 22, 2015 at 1:19 AM, FrostbittenKing
> <notifications@github.com> wrote:
> > [quote]Tracked this down to something else actually.. we were
requesting an
> > LDT slot in a seperate call with an otherwise-zeroed user_desc. This is
> > apparently now illegal.
> > [/quote]
>
> Also see
>
>
http://steamcommunity.com/app/20920/discussions/0/620700960252675402/#c616199736993636877
>
https://github.com/KillaW0lf04/The-Witcher-2-Issues/issues/89#issuecomment-70829298
>
> so we'll need to revert or relax it. Possibly some of the checks could
> be optional, so that they could just be disabled on servers etc who
> worry more about attack surfaces than about games.
>
> Can somebody specify exactly what the LDT entry was? The github email
> address hopefully reaches a game developer too (Peter Mulholland). It
> would be nice to keep the checks tight - just not *too* tight. And no,
> you guys should *not* need to change user space app details, because
> the kernel "don't break apps" rule really takes precedence.
>
> And maybe this is an excuse for somebody in the x86 maintainer team to
> try a few games on steam. They *are* likely good tests of odd
> behavior..

It looks like LDT_empty is buggy on 64-bit kernels.  I suspect that the
behavior was inconsistent before the tightening change and that it's now
broken as a result.  I'll write a patch.

Serves me right for not digging all the way down the mess of macros.

--Andy

**Comment by vpltd-peterm** [comment]
@torvalds We were doing this..

```
static int get_selector_for_teb_entries( void )
{
    static int process_fs_selector = -1;
    if( process_fs_selector == -1 )
    {
        // This should allocate this entry in all future threads (even not eON2 threads), with dummy info
        // This way, each our future thread will know it can use this entry's index in LDT as a place to store info about its own TEB

        struct user_desc u_info;
        bzero( &u_info, sizeof(u_info) );
        u_info.entry_number = (uint32_t)-1;		// let the kernel pick one

        EON_ASSERT_CALL_RESULT( syscall( SYS_set_thread_area, &u_info ), 0 );
        process_fs_selector = u_info.entry_number;
        EON_LOG_DEBUG( "LDT table index for TEB entries determined to be %d", process_fs_selector );
        EON_ASSERT( process_fs_selector != -1 );
    }

    return process_fs_selector;
}
```

and later using this inside the setup_teb_register() function I posted earlier. I know it is unnecessary for it to be a two-step process, but it did work until recently.

**Comment by amluto** [comment]
There are a couple of issues.  One of them should be fixed by:

https://git.kernel.org/cgit/linux/kernel/git/luto/linux.git/commit/?h=x86/tls&id=ded5964c8a115a4645ed17f687e38828c7954f86

I suspect that we need that fix but that it's not good enough.  Everyone seems to think that all zeros means "empty descriptor" (including me), but that's not how the code works.  We may need to special-case all zeros, but that's nasty, because all zeros is actually a valid 16-bit segment.  Ugh.  We could special case it just for set_thread_area, I guess.

Side note: your comments are confused.  set_thread_area manipulates the GDT, not the LDT.

**Comment by vpltd-peterm** [comment]
OK, the comments were likely written in light of our Mac code. On OS X we are allocating an LDT entry with i386_set_ldt() to do the same job. The effect is the same, I believe.

**Comment by amluto** [comment]
Could one of you test these two commits on top of an up-to-date kernel (stable should be fine, but I haven't checked whether it applies to the problematic stable releases) with a problematic build of The Witcher 2:

https://git.kernel.org/cgit/linux/kernel/git/luto/linux.git/commit/?h=x86/tls&id=164e032239eae3163041f50d668c44e48ecf7287

https://git.kernel.org/cgit/linux/kernel/git/luto/linux.git/commit/?h=x86/tls&id=83b0849b38a3badaada90807ab8d7b3a4c31b9f6

Thanks,
Andy

**Comment by FrostbittenKing** [comment]
Yep, will test it.

**Comment by FrostbittenKing** [comment]
Ok, confirmed. Patches work.

**Comment by vpltd-peterm** [comment]
Cool, nice to know :) We will still ship an update. This should be ready by Friday at the latest.

**Comment by FrostbittenKing** [comment]
Great. Glad this is fixed now.

**Comment by amluto** [comment]
FWIW, as the offending kernel developer, I can explain my agenda :)  I was chasing down some really nasty segmentation-related issues (CVE-2014-9090, CVE-2014-9322, and others), and, in the process, I discovered that set_thread_area could be abused to do things that it was never intended to allow, and that some of those things were actively dangerous.

Fixing these kinds of issues is tricky.  On the one hand, the rule is quite clear: Linux doesn't break working programs.  On the other hand, leaving security holes open because I'm afraid of touching an ABI isn't so good either.  So I tried to tighten up the interface without breaking legitimate use cases.  Unfortunately, I didn't realize that bzeroing a struct user_desc and passing it into set_thread_area would have worked in the past and now would fail.  (Actually, you were successfully running the first part of a kernel exploit, as the all-zero user_desc corresponds to a descriptor that, due to a really old design error on Intel's part, causes problems in the GDT.  Congrats!  The next step in the exploit would be to load the corresponding selector into SS and do an int 80 or otherwise trap into the kernel by any means other than a fast system call.  So I either had to block the exploit on exit from the kernel, which would slow everything down and add a bunch of complexity, or I had to change set_thread_area.)

The only problem with closed-source software here is that searching the Internet for set_thread_area didn't find your use case. :(

**Comment by vpltd-peterm** [comment]
Yeah that was a  comment I made after a bad day and an argument with a really stupid user. My apologies. Quite frankly, I am impressed that the kernel team even noticed us ;)

I have amended the affected code now, as there was no reason for it to be a two pass operation. Hopefully, we should now be doing the right thing too!

We are due to push an update either tonight (UK time) or tomorrow. I'm working on tidying things up currently for a new release.

**Comment by amluto** [comment]
No problem.  I never saw the original comment in the first place, actually.

If you ever have issues with Linux kernel stuff in the future when porting
or maintaining games, please let us (i.e. linux-kernel and, if it's an
x86-specific thing, cc me) know.  Games seem to do crazy things, in a good
way, and knowing what use cases are out there is very helpful.

--Andy

On Thu, Jan 22, 2015 at 11:58 AM, Peter Mulholland <notifications@github.com

**Comment by vpltd-peterm** [comment]
Our latest beta is out now, and this includes the fixed usage of SYS_set_thread_area I described above. So hopefully between the two of us, there is no longer any problem :)

**Comment by vpltd-peterm** [comment]
Tested here on Fedora 20, kernel 3.17.80299.fc20.x86_64, using nvidia driver 346.35 and the game is running correctly.

**Comment by Hernanarce** [comment]
hi, sorry for ask but, how i can get the public beta, to test if works

**Comment by eydee** [comment]
@Hernanarce:
Right click the game in Steam, select properties, go to the betas tab and there you can opt in.

**Comment by Hernanarce** [comment]
ok, but i have the GOG version, is there another way to get it?

**Comment by eydee** [comment]
@Hernanarce:
No idea. Contact GOG support I guess.

**Comment by abc-mikey** [comment]
Latest kernel update on Fedora (3.18.5-201.fc21.x86_64) seems to have it running again for me. However it seems to be running worse than before. This may however be coincidental. 

Prior to the kernel update I contacted GOG whose representative said that they were waiting on the developer to supply them with a DRM free version of the patch. The last patch, for this infamously buggy conversion, on GOG appears to be from September. I've found issues with the voice files not being loaded because the game seems to be looking for the media with the wrong case in the name! I still haven't found a fix that would fix the sullen silences that accompany the obvious narration points. Could perhaps the developers behind the port and GOG actually talk to each other and sort this out?

**Comment by eydee** [comment]
@abc-mikey:
Check out the the readme.md file on this bugtracker, new binaries are now linked in the update notes for GOG users.

**Comment by abc-mikey** [comment]
Thanks.

**Comment by Hernanarce** [comment]
Thanks with the new patch it's works for me.

**Comment by mibon** [comment]
Game crashes with same error under ubuntu 14.04. Is it possible that this fix is not available in GoG edition?

**Comment by vpltd-peterm** [comment]
Please see the front page - a beta update for the GOG version is available there

**Comment by mibon** [comment]
got it already. thanks for that
