### ISSUE TITLE
Add Gallium Nine support

### ISSUE THREAD

**Issue by eydee** [KillaW0lf04/The-Witcher-2-Issues#90]
Now that the DX9 state tracker is in Mesa, using this feature when available would be nice. Wine can do it, so probably the EON wrapper could also do it and the performance would probably be very much better than with the OGL wrapper. (It could be a fallback in case it's not available on the user's computer.)

**Comment by vpltd-peterm** [comment]
It's possible, but unlikely.. the MESA drivers are still quite behind on supporting recent hardware so this is just not time well spent for us.

**Comment by kvark** [comment]
@vpltd-peterm Could you please give us an update? What's cooking, if anything? I don't see any news since September, though I recall promises about pushing AMD performance a bit further.

**Comment by cheako** [comment]
Open issues should only be closed after a resolution that's beneficial to the party who opened the issue.  If you want "Won't fix" or "Needs Help" that's understandable, but neither of these are anywhere near the same as Closed.

I stand behind #123, users who encounter an issue have every right to stop looking for the issue in the tracker at the point where finding a previous issue means sifting through all the closed issues.  Closed indicates that the issue is dealt with and if something similar happens that it's more then likely a NEW issue.  Closed also assists users reporting Issues in that it's a flag that indicates, this issue has nothing to do with new issues and can be ignored if you are reporting one.  This level of record keeping simplifies the process of Reporting new issues, as when there are many thousand Issues searching all the closed ones to report a new one is daunting and unreasonable.

Only the original parties should re-open Closed issues if the problem persists or the provided solution isn't usable or applicable.

**Comment by cheako** [comment]
"MESA drivers are still quite behind on supporting recent hardware"

Did you check a recent release?  Could you say what hardware you are running, it's difficult to help if you don't provide enough information.

**Comment by vpltd-peterm** [comment]
As far as I am aware, none of AMD's GCN hardware is fully supported by MESA yet. None of Nvidia's hardware is well supported by Nouveau, not when you are talking about high performance games at least.

**Comment by cheako** [comment]
Try again, my testing shows that Witcher 2 runs great at low and playable at medium settings with both MESA 10.3.2(jessie) and MESA 10.4.2(current sid) using a 3.16.0 kernel.

IMHO I wouldn't put much stock in "fully supported" ratings, usually the important stuff is implemented first so even partial support can put the closed drivers to shame.  For example, D3D9 support is important...  How many closed drivers claim any support?

**Comment by vpltd-peterm** [comment]
On what hardware ? If you are using older AMD Terascale hardware (5xxx, 6xxx and the 7xxx series under 7700) then yes, the r600 mesa driver works quite well for OpenGL 3.2 level apps. For modern GCN hardware such as the 7750 and the R7/R9 series cards, radeonsi does not work well at all. I tested both of these alongside fglrx during development.

**Comment by cheako** [comment]
See: #123
R7 250X 2GB DDR5, this _is_ the 2GB ASUS card.
Perhaps you didn't have a new enough kernel?

**Comment by vpltd-peterm** [comment]
It is my understanding that you need to run very bleeding edge stuff to get this - either you need to be comfortable installing kernels by yourself, or run a rolling release distro such as Arch (I use Antergos for testing). A lot of Linux gamers are using distro's such as Ubuntu which go for stability over bleeding edge, and do not have access to these features. I tested much newer Mesa stuff via the "oibaf" PPA on Ubuntu, and still found the performance to be disappointing.

Also remember that Witcher 2 is now a year old from it's release. At the time of it's development, Mesa was not capable of running the game at all. From customer feedback, I now know that r600 is, but have not heard anything good about radeonsi. If it supports the newer hardware well enough to run the game now, that is good.

I do note that your specs posted in #123 suggest your driver only supports OpenGL 3.0. This means you are getting our OpenGL 2.1 renderer, rather than our OpenGL 3.2 renderer. This fallback will impact performance.

Ultimately, we discussed Gallium Nine support in house, and determined it is just not an effective use of our dev time, currently. A lot of hardware is still not well supported by Mesa, and there are relatively few Linux gamers able to use it. 

Ultimately, we are looking forward to Vulkan, and implementing rendering technology with this.

**Comment by cheako** [comment]
Thanks for the time, tips, quick response and updates, all much appreciated.  I think you should re-open #90 to prevent anyone from creating another issue like #123.

This system is mostly Wheezy didn't even have MESA from Sid till I noticed that I couldn't even test Gallium Nine without it.  I'm not running anything I compiled myself.  I'll look to testing the OpenGL 3.2 renderer and report back.
